os: linux
language: node_js
node_js:
  - 'stable'
cache:
  npm: true

jobs:
  include:
    - stage: deploy-to-gh-pages
      install:
        - npm install
      cache:
        directories:
          - 'build'
      script:
        - npm run build
      deploy:
        edge: true
        cleanup: false
        provider: pages
        token: $GITHUB_TOKEN
        keep_history: true
        target_branch: master
        local_dir: './build'
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(build)$
