name: GitHub Pages deploy
on:
  push:
    branches:
      - build
  pull_request:
jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          npm install
          npm run build
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@master
        env:
          EMAIL: seanchok@gmail.com
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: build/
          CNAME: seanchok.com
